name: Update Changelog Manual

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Grant write permissions for the repository contents

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all releases
        id: fetch_releases
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/${{ github.repository }}/releases > releases.json
          echo "Fetched releases.json:"
          cat releases.json # Debug: output the contents of releases.json

      - name: Generate changelog content
        run: |
          python3 generate_changelog.py

      - name: Update README with Changelog
        run: |
          changelog=$(cat changelog.txt)
          awk -v changelog="$changelog" '
            BEGIN { start = 0 }
            /<!-- changelog-start -->/ { print; print changelog; start = 1; next }
            /<!-- changelog-end -->/ { start = 0 }
            !start { print }
          ' README.md > README_new.md
          mv README_new.md README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update changelog manually"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
